// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaQ5-fLXa6oHL_BnrIZ0kQh5ykUaAYP_8',
    appId: '1:626187938085:web:8e7221bb68fc95b8ef52cc',
    messagingSenderId: '626187938085',
    projectId: 'planner-maker',
    authDomain: 'planner-maker.firebaseapp.com',
    storageBucket: 'planner-maker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg2VN4R3fXwZ8C6B72PS9IoqU54AN7Vfo',
    appId: '1:626187938085:android:6f06fc860df679c2ef52cc',
    messagingSenderId: '626187938085',
    projectId: 'planner-maker',
    storageBucket: 'planner-maker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU4WgwcWGrvyAEugRq16waEzvxinh2PU4',
    appId: '1:626187938085:ios:a3ff235f94fa4596ef52cc',
    messagingSenderId: '626187938085',
    projectId: 'planner-maker',
    storageBucket: 'planner-maker.appspot.com',
    iosClientId: '626187938085-cspnh08dsndtdco4s15kgsgc9aec2rm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.plannner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU4WgwcWGrvyAEugRq16waEzvxinh2PU4',
    appId: '1:626187938085:ios:a3ff235f94fa4596ef52cc',
    messagingSenderId: '626187938085',
    projectId: 'planner-maker',
    storageBucket: 'planner-maker.appspot.com',
    iosClientId: '626187938085-cspnh08dsndtdco4s15kgsgc9aec2rm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.plannner',
  );
}
